---
title: "Progress Report"
author: "Karl von Zabern, ChihChin Yang, SzuWei Fu, Evan Bowman"
date: '`r Sys.Date()`'
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### <span style="color: blue;">Report.1. Admin:</span>
#### -  App Title: `DC Heat Sensitivity Mapping`

#### -  Names and course of the group members:

- Karl von Zabern - DATA 613-001
- ChihChin Yang - DATA 613-001
- SzuWei Fu - DATA 613-001
- Evan Bowman - DATA 613-001
     
### <span style="color: blue;">Report.2. Topic and Data:</span>
#### -  Updates on the description of the problem to be analyzed in the Shiny App: 

Our group has decided to switch our data sets following the difficulty in merging the previous water source data. There were issues in finding enough quantitative variables to be able to present the tools for meaningful analysis. Furthermore, the quantitative variables found within the water data set were very sporadic in their inputs, with only a few inputs for specific countries. This would prohibit us from doing an international analysis as only a few cities would have enough data to visualize. 

We have decided to shift to a more locally focused data set that analyzes heat sensitivities across DC census tracts. The data was found on Open Data DC and has a variety of sociodemographic variables for each census tract (percent poverty, percent people of color, etc.), as well as some environmental variables explaining heat indexes (percent impervious surface, percent tree color, mean air temperature, etc.). 

Our idea regarding the shiny app is to be able to statistically model specific correlates of the Heat Sensitivity Exposure Index (HSEI). HSEI is an environmental metric that is a combination of heat sensitivity index and heat exposure index and is used to highlight individuals' threat of health risks from high temperatures. These correlates can then be taken and used to explore any socio-demographic trends that are prevalent on a census tract basis. 



#### - Updates on the literature review:
Benz, Susanne Amelie, and Jennifer Anne Burney. 2021. “Widespread Race and Class Disparities in Surface Urban Heat Extremes Across the United States.” Earth’s Future 9 (7): e2021EF002016.
Chakraborty, T, A Hsu, D Manya, and G Sheriff. 2020. “A Spatially Explicit Surface Urban Heat Island Database for the United States: Characterization, Uncertainties, and Possible Applications.” ISPRS Journal of Photogrammetry and Remote Sensing 168: 74–88.
Hsu, Angel, Glenn Sheriff, Tirthankar Chakraborty, and Diego Manya. 2021. “Disproportionate Exposure to Urban Heat Island Intensity Across Major US Cities.” Nature Communications 12 (1): 1–11.

 
### <span style="color: blue;">Report.3. Final Use Case:</span>
#### - Actor Description: 

The actor for this app will most likely be someone within the DC government’s Department of Energy and Environment or Health and Human Services. The purpose of the visual representation and statistical modeling would be to assist in the formulation of policy that attempts to mitigate the occurrences of heat-related health incidences.  
 
#### - Questions of Interest: 

The use of this data frame lends itself to several questions regarding the correlates that exacerbate extreme heat and the communities most affected. Thus, our app will assist in understanding of two specific questions:
What are environmental metrics that are correlated with Urban Heat Island Effects? 
What environmental characteristics of certain census tracts create larger heat exposure sensitivity indexes? Understanding the environmental factors would help in identifying policy approaches that would mitigate the probability of heat-induced health events. 
What are recurring socio-demographic trends that are associated with higher heat exposure sensitivity indexes? 
Who are the communities that are at a larger risk of heat-induced health events? Identifying socio-demographic trends can assist policymakers in identifying the communities that would best benefit from policy implementation.

 
#### - Choice of approach to data: 

Our approach is to be able to map different socio demographic metrics and environmental metrics to different Census tracts. This will allow the user to be able to visualize different metrics and how they differentiate between census tracts in DC. The modeling will also help shed insight on why these visual discrepancies exist. 

### <span style="color: blue;">Report.4. App Design:</span> 
#### - General Layout with specific Tabs and Panes within Tabs:

The draft layout is in the draft shiny app. We plan on having four tabs: Bivariate Analysis, Maps, Statistical Modeling, and Full Data. Each will have a specific role in creating a comprehensive understanding of the data.

### <span style="color: blue;">Report.6. Ethical Review:</span> 
#### - Update of ethics review:
 
Data from DC OpenData “does not guarantee the completeness, accuracy, content, or fitness for any particular purpose”. We as the app developers, and DC, are not liable for any deficiencies in the completeness, accuracy, content, or fitness for any particular purpose or use of the public data set. Since our app uses data from “DC OpenData”, we need to pass this message on to the users

### <span style="color: blue;">Report.7.Demonstration Outline and Responsibilities:</span> 
#### - Outline, Who, and Time Allocation:

- Data Cleaning and tidying: Evan. Completed. 
- Shiny layout (Bivariate Analysis and Maps): Karl and Evan. One hour per day.
- Shiny layout (Statistical Modeling): Alexia and Adela: The draft layout is found in the Shiny App folder. 30 min per day.
-  Literature Review: Karl. 1 hour per day.
- Vignette: Evan. TBD depending on completion of Shiny.
   
### <span style="color: blue;">Report.8. Collaboration:</span>  
#### - Status of collaboration and any issues

The new data frame allows us to begin work on the Shiny app right away. Data is already tidied and merged with the correct shape files to be able to render polygons with the leaflet. This keeps us on track with our original timeline of beginning the Shiny build-out this week. 


### <span style="color: blue;">Report.9. Schedule and Risk Mitigation:</span>  
#### - Identify any major risks to completion and proposed mitigation measures

There seem to be relatively few risks to completion now that we have a workable data set that has been successfully manipulated to contain all of the required variables. 

One risk is the interactive map build out using Leaflet due to the general lack of familiarity with the package. To mitigate this, Karl and Evan will put priority on building out this tab first before the bivariate analysis tab to ensure ample time is given to complete it.
 
#### - Updated Dates for Major Phases and Milestones:

November 27: Initial build-out of each Shiny tab with base-level modeling and graphical outputs rendered. This will allow us to have a two-week window to work on some more complex renderings for the Shiny app.

December 7: Final pushes to GitHub for each tab. This will give us four days to be able to discuss minor changes in the Shiny output, as well as collaborate on the Vignette and presentation preparation.

December 11: Final changes on the Vignette. Group collaboration on any minor changes. Last day for project preparation

