---
title: "Project Plan"
author: "Karl von Zabern, ChihChin Yang, SzuWei Fu, Evan Bowman"
date: "`r Sys.Date()`"
output: html_document
---

### APP Title: City Water Exploration

#### Team members:

- Karl von Zabern - DATA 613-001
- ChihChin Yang - DATA 613-001
- SzuWei Fu - DATA 613-001
- Evan Bowman - DATA 613-001

#### Topic and Data:

This is an initial exploration of a data set put together by researchers at the Nature Conservancy published by McDonald et al. (2011). This project will make these data more accessible to researchers, policymakers, civil society actors, and more by creating an interface that will allow them to analyze data related to water based on different units of analysis. These data are extremely useful for better understanding the ways in which water resource stress exists in different locations, and how that stress manifests in varying water infrastructure projects globally. Furthermore, we will visualize data to prepare for econometric modeling.

This data set shows over 1,500 water intake locations from the first global survey of the water sources of over 500 large cities. The data set was created and published by Rob McDonald and The Nature Conservancy from research on water utilities and their annual reports. For each intake location, spatial location was recorded. The locations were recorded as accurately as possible, and freshwater withdrawal points were adjusted to match the underlying hydrographic river system. Some intake points serve multiple water utilities and cities. Resource Watch shows only a subset of the data set.

	The literature on water scarcity related to climate change has long been concerned that climate change will drive political struggles over down stream and upstream users ().

#### Proposed data sources:

The data used for this shiny app will come from the McDonald et al. 2014 paper. This data set shows over 1,500 water intake locations from the first global survey of the water sources of over 500 large cities. The data set was created and published by Rob McDonald and The Nature Conservancy from research on water utilities and their annual reports. For each intake location, spatial location was recorded. The locations were recorded as accurately as possible, and freshwater withdrawal points were adjusted to match the underlying hydrographic river system. Some intake points serve multiple water utilities and cities. The data is from WaterGAP to assess water availability of water from time series climatic data. 


The data is intended to give users the ability to understand three components of water access: water availability, water quality, and delivery. Water availability refers purely to the amount of water physically available to a city. This measure informs the overall level of water stress by city. This measure does not account for the quality  of water sources nor mechanisms for water delivery. 


#### Literature review:

McDonald, R. I., Weber, K., Padowski, J., Flörke, M., Schneider, C., Green, P. A., ... & Montgomery, M. (2014). Water on an urban planet: Urbanization and the reach of urban water infrastructure. Global environmental change, 27, 96-105.

#### Actor/Audience Description:

This App may tend best to city government officials and policy makers. They will be able to see which locations need more resources based on the map and statistical analysis.

#### Fixed or Dynamic Data:

The data for this project is fixed. Data collection for this projects came from decentralized sources and therefore required a large amount of labor to put into a cohesive, comparable format.

#### Questions of Interest:

1. What is the water source distributed in the global city?
2. Compare water source from developed and not developed city
3. What is the size of water used from urban instructure around the world and the percentage of water used from earth surface?



#### General Layout:

We will have 1 tab for an interactive map that will allow users to manipulate what variable they want to see and. Another tab will have tables for statistical analysis and summary, which users will be able to select which variable they want to analyze. The last tab will contain the sampled data.

#### APP Theme: 

We will use the Cosmo theme from Bootswatch.

#### Ethics review:

Data from Nature Conservancy published by McDonald et al. (2011) does not warranty the completeness, accuracy, content, or fitness for any particular purpose”. We as the app developers, are not liable for any deficiencies in the completeness, accuracy, content, or fitness for any particular purpose or use of the public data set. Since our app uses data from Nature Conservancy published by McDonald et al. (2011),  we need to pass this message onto the users.

#### Jobs:

We segmented certain tasks among the group, but we will work with each other if additional help is needed.

- Karl von Zaborn: Literature review, Shiny coding-map tab
- ChihChin Yang: Data cleaning, Shiny coding-statistics tab
- SzuWei Fu: Data cleaning, Shiny coding-statistics tab
- Evan Bowman: Shiny coding-map tab, vignette

We will collaborate and communicate over Zoom and WhatsApp.Regarding branching, each person will have their own branch. 1 person will push the main branch when we have a group meeting and we can merge to pull the latest submission/push.

#### Schedule:

- Data Cleaning and exploration and Peer Review: 11/1
- Data manipulation and shiny structure and Prog Report: 11/8
- Rough draft of app and Vignette: 11/15
- Rehearsals: 11/29
- Push to GitHub: 12/6

